id: A0C2C10CC
title: 'The Lightning Bolt of Compassion: A Short Prayer that Spontaneously Fulfils
  All Wishes (Sampa Lhundrupma)'
type: translation
source_metadata:
  languages:
  - en
  - de
  - es
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-02-28 22:56:06.870380
  last_modified_at: 2022-02-28 22:56:06.870384
