id: A0C2C10CC
title: 'The Hook Which Invokes the Blessings: A Supplication to the Life and Liberation
  of Rigdzin Jalü Dorje'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 22:56:06.867605
  last_modified_at: 2022-02-28 22:56:06.867633
