id: A0C2C10CC
title: Heart of Vajrasattva—The Heart of Confession, the King of Purification Practices,
  from 'The Immaculate Secret Vajrasattva'
type: translation
source_metadata:
  languages:
  - en
  - de
  - es
  - fr
  - it
  - nl
  - zh
  - bo
  datatype: PlainText
  created_at: 2022-02-28 22:56:06.862418
  last_modified_at: 2022-02-28 22:56:06.862425
