id: A0C2C10CC
title: The Lineage Prayer for the Natural Liberation of Grasping (Dzinpa Rangdrol)
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 22:56:06.873160
  last_modified_at: 2022-02-28 22:56:06.873167
