id: A0C2C10CC
title: 'The Truthful Words of a Sage: An Aspiration Prayer from the Exceedingly Secret,
  Enlightened Heart-Essence of the Ḍākinī'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 22:56:06.881360
  last_modified_at: 2022-02-28 22:56:06.881363
